name: Deploy

on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    environment: prod

    steps:
      - uses: actions/checkout@v5
      - name: Use Node.js
        uses: actions/setup-node@v5
        with:
          node-version: 22.x
          cache: "npm"
      - run: npm ci
      - name: Make envfile
        uses: SpicyPizza/create-envfile@v2.0.3
        with:
          envkey_DISCORD_BOT_TOKEN: ${{ secrets.DISCORD_BOT_TOKEN }}
          envkey_DISCORD_BOT_CLIENT_ID: ${{ secrets.DISCORD_BOT_CLIENT_ID }}
      - run: npm run ci:build
      - name: rsync deployments
        uses: burnett01/rsync-deployments@7.1.0
        with:
          switches: -a --delete
          path: out/
          remote_path: /etc/discord-red-roller/
          remote_host: 159.223.213.54
          remote_user: root
          remote_key: ${{ secrets.DEPLOY_KEY }}
